import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Mobile from "@/components/Mobile";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "RealEstate App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="drawer drawer-end h-screen">
          <input id="my-drawer" type="checkbox" className="drawer-toggle" />
          <div className="drawer-content">
            <Navbar />
            <div className="h-[calc(100vh-100px)] px-5 lg:px-10">
              {children}
            </div>
          </div>
          <div className="drawer-side md:hidden">
            <label
              htmlFor="my-drawer"
              aria-label="close sidebar"
              className="drawer-overlay"
            ></label>
            <Mobile />
          </div>
          <Toaster />
        </div>
      </body>
    </html>
  );
}
